### ISSUE TITLE
Differentiation of upgraded connections

### ISSUE THREAD

**Issue by briantopping** [wandoulabs/spray-websocket#45]
I am having a problem discovering how to differentiate connections that need upgrade.  My intuition is the URI of the upgraded resource should provide the means to multiplex between multiple connections.  

Because of the state machine architecture, this should be as simple as changing the businessLogic signature from Actor.Receive to a partial function accepting a path and returning an Actor.Receive.  I took a stab at implementing it, but I can't find a good source for the request path. It seems to exist as late as https://github.com/topping/spray-websocket/blob/master/spray-websocket/src/main/scala/spray/can/websocket/WebSocketServerConnection.scala#L33-33, but beyond that, the path needs to be propagated.  I could create a PR, but I'd imagine it could be improved on by @dcaoyuan so it may be a waste of time for both of us.

Thoughts?

**Comment by Alain-Bearez** [comment]
Brian,

I took a different approach in order to make almost what you described. I use the standard route mechanism from Spray in order to "register" a specific handler actor through a generic WebSocketServerWorker started on each request, using the per-request actor pattern.

You might want to take a look at my code at:
https://github.com/cuali/SprayEasterEggs/blob/wandoulabs/src/main/scala/reactive/websocket/WebSocketServer.scala#L22

Best regards,
Alain

**Comment by briantopping** [comment]
@Alain-Bearez: thanks!
